### ISSUE TITLE
Engine requirement

### ISSUE THREAD

**Issue by pyrocat101** [rocicorp/fractional-indexing#4]
👋 Thanks for creating this. I wonder why the Node.js engine requirement is >= 13?

**Comment by aboodman** [comment]
Good question. Couldn’t find anything relevant in node 13 release notes or corresponding v8. @arv?

**Comment by arv** [comment]
No good reason any more

Maybe I added it when we were using JS modules?

**Comment by aboodman** [comment]
@arv I made the change to the code but I don't have access to publish. Can you give me access?

**Comment by arv** [comment]
@aboodman invited

**Comment by lennartnederstigt** [comment]
Awesome, thanks for making the changes! 👍 @aboodman could you publish the new version?

**Comment by aboodman** [comment]
This is live now as 2.1.0 on npm, sorry it took so long.
